CaseStudy/WebApps/OdeToFood/ViewComponents/RestaurantCountViewComponent.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

using OdeToFood.Core.Interfaces;
using OdeToFood.Core.Models;
using OdeToFood.ViewModels;

namespace OdeToFood.ViewComponents
{
   public class RestaurantCountViewComponent : ViewComponent
   {
      private readonly IRestaurantRepository _restaurantRepository;

      public RestaurantCountViewComponent(IRestaurantRepository restaurantRepository, IHtmlHelper htmlHelper)
      {
         _restaurantRepository = restaurantRepository ?? throw new ArgumentNullException(nameof(restaurantRepository));
      }

      public async Task<IViewComponentResult> InvokeAsync(CuisineType? cuisineType)
      {
         var response = new RestaurantCountViewModel()
         {
            Count = await _restaurantRepository.CountAsync(cuisineType),
            CuisineType = cuisineType
         };

         return View(response);
      }
   }
}

CaseStudy/WebApps/OdeToFood/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
   <meta charset="utf-8" />
   <meta name="viewport" content="width=device-width, initial-scale=1.0" />
   <title>@ViewData["Title"] - OdeToFood</title>

   <environment include="Development">
      <link rel="stylesheet" href="~/node_modules/bootstrap/dist/css/bootstrap.css" />
      <link rel="stylesheet" href="~/node_modules/@@fortawesome/fontawesome-free/css/all.css" />
      <link rel="stylesheet" href="~/css/site.css" />
   </environment>
   <environment exclude="Development">
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            asp-fallback-href="~/node_modules/bootstrap/dist/css/bootstrap.css"
            asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
            crossorigin="anonymous"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
      <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
   </environment>

   @RenderSection("Styles", required: false)
</head>
<body>
   <header>
      <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
         <div class="container">
            <a class="navbar-brand" asp-area="" asp-page="/Index">OdeToFood</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
               <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
               <ul class="navbar-nav flex-grow-1">
                  <li class="nav-item">
                     <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link text-dark" asp-area="" asp-page="/Restaurants/List">Restaurants</a>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link text-dark" asp-area="" asp-page="/ClientRestaurants/List">Restaurants (client-side view)</a>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link text-dark" asp-area="" asp-page="/About">About</a>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link text-dark" asp-area="" asp-page="/Contact">Contact</a>
                  </li>
               </ul>
            </div>
         </div>
      </nav>
   </header>
   <div class="container">
      <partial name="_CookieConsentPartial" />
      <main role="main" class="pb-3">
         @RenderBody()
      </main>
   </div>

   <footer class="border-top footer text-muted">
      @RenderSection(name: "footer", required: false)
      <div class="container">
         <div class="row">
            <div class="col col-md-12 col-lg-6">
               <div class="float-md-none float-lg-left">
                  <vc:restaurant-count cuisine-type="@CuisineType.VietNamese"></vc:restaurant-count>
               </div>
            </div>
            <div class="col col-md-12 col-lg-6">
               <div class="float-md-none float-lg-right">
                  &copy; 2019 - OdeToFood - <a asp-area="" asp-page="/Privacy">Privacy</a>
               </div>
            </div>
         </div>
      </div>
   </footer>

   <environment include="Development">
      <script src="~/node_modules/jquery/dist/jquery.js"></script>
      <script src="~/node_modules/bootstrap/dist/js/bootstrap.bundle.js"></script>
      <script src="~/js/site.js" asp-append-version="true"></script>
   </environment>
   <environment exclude="Development">
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"
              asp-fallback-src="~/node_modules/jquery/dist/jquery.min.js"
              asp-fallback-test="window.jQuery"
              crossorigin="anonymous"
              integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
      </script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
              asp-fallback-src="~/node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
              asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
              crossorigin="anonymous"
              integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
      </script>
      <script src="~/js/site.min.js" asp-append-version="true"></script>
   </environment>

   @RenderSection("Scripts", required: false)
</body>
</html>